### ISSUE TITLE
언노운워드에 관한 문의

### ISSUE THREAD

**Issue by joonroot** [Preta-Crowz/Prj_KT#18]
저는 일반끄투레포지토리에 언노운워드를 추가하고싶습니다 그러려먼 어떻게해야하는지 알려주실수 있나요?

**Comment by Preta-Crowz** [comment]
해당 레포지토리에서 언노운워드 관련 소스코드만을 찾아, 기본 소스코드에 작성하여야합니다. 아무런 코딩 지식 없이는 작업이 힘들 수 있습니다.
